name: build-website

on:
  workflow_call:

jobs:
  build-application:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Build publishable website
        run: |
          dotnet publish --configuration Release
        working-directory: ./src/MyCompany/MyCompany.Website

      - name: Zip publishable website
        run: |
          zip -r publish.zip .
        working-directory: ./src/MyCompany/MyCompany.Website/bin/Release/netcoreapp3.1/publish

      - name: Upload website as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./src/MyCompany/MyCompany.Website/bin/Release/netcoreapp3.1/publish/publish.zip

  build-database:
    name: Build database
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1

      - name: Prepare MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Build database project
        working-directory: ./src/MyCompany/MyCompany.Database
        run: MSBuild.exe MyCompany.Database.sqlproj -property:Configuration=Release

      - name: Upload website as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: database
          path: ./src/MyCompany/MyCompany.Database/bin/Release/MyCompany.Database.dacpac
