name: deploy-my-website-end2end
concurrency: my-company

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build the application and database.
  build:
    uses: ccie9773/my-website-end2end/.github/workflows/build.yml@main

  # Lint the Bicep file.
  lint:
    uses: ccie9773/my-website-end2end/.github/workflows/lint.yml@main

  # Deploy to the test environment.
  deploy-test:
    uses: ccie9773/my-website-end2end/.github/workflows/deploy.yml@main
    needs: [build, lint]
    with:
      environmentType: Test
      resourceGroupName: MyWebsiteTest
      reviewApiUrl: https://sandbox.contoso.com/reviews
      sqlServerAdministratorLogin: TestMyCompanyAdmin
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_TEST }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_TEST }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_TEST }}

  # Deploy to the production environment.
  deploy-production:
    uses: ccie9773/my-website-end2end/.github/workflows/deploy.yml@main
    needs:
      - lint
      - build
      - deploy-test
    with:
      environmentType: Production
      resourceGroupName: MyWebsiteProduction
      reviewApiUrl: https://api.contoso.com/reviews
      sqlServerAdministratorLogin: MyCompanyAdmin
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
      reviewApiKey: ${{ secrets.REVIEW_API_KEY_PRODUCTION }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQL_SERVER_ADMINISTRATOR_LOGIN_PASSWORD_PRODUCTION }}
